const tech = [
  "Google Chrome",
  "Safari",
  "Firefox",
  "Internet Explorer",
  "HTML",
  "CSS",
  "LESS",
  "SASS",
  "Javascript",
  "Coffeescript",
  "Python",
  "Ruby",
  "PHP",
  "Go",
  "Objective-C ",
  "Swift",
  "Java",
  "Meteor",
  "Node.js",
  "Ruby on Rails",
  "Django",
  "Ionic",
  "Phonegap / Cordova",
  "Bootstrap",
  "Foundation",
  "Wordpress",
  "Drupal",
  ".NET",
  "Angular.js",
  "Ember.js",
  "Backbone.js",
  "jQuery",
  "Underscore",
  "MongoDB",
  "Redis",
  "PostgreSQL",
  "MySQL",
  "Oracle",
  "SQL Server",
  "HTTP",
  "DDP",
  "REST",
  "JSON",
  "XML",
  "CSV"
];

const creatures = [
  "Aberration",
  "Animal",
  "Celestial",
  "Construct",
  "Dragon",
  "Elemental",
  "Fey",
  "Fiend",
  "Giant",
  "Humanoid",
  "Magical Beast",
  "Monstrous Humanoid",
  "Ooze",
  "Outsider",
  "Plant",
  "Undead",
  "Vermin",
  "Lawful Good",
  "Neutral Good",
  "Chaotic Good",
  "Lawful Neutral",
  "Neutral",
  "Chaotic Neutral",
  "Lawful Evil",
  "Neutral Evil",
  "Chaotic Evil",
  "Air",
  "Angel",
  "Aquatic",
  "Archon",
  "Augmented",
  "Chaotic",
  "Cold",
  "Demon",
  "Devil",
  "Earth",
  "Evil",
  "Extraplanar",
  "Fire",
  "Good",
  "Incorporeal",
  "Lawful",
  "Native",
  "Psionic",
  "Shapechanger",
  "Swarm",
  "Water",
  "Aquatic",
  "Dwarf",
  "Elf",
  "Gnoll",
  "Gnome",
  "Goblinoid",
  "Halfling",
  "Human",
  "Orc",
  "Reptilian",
  "Aberration",
  "Animal",
  "Construct",
  "Dragon",
  "Elemental",
  "Fey",
  "Giant",
  "Humanoid (aquatic)",
  "Humanoid (dwarf)",
  "Humanoid (elf)",
  "Humanoid (goblinoid)",
  "Humanoid (gnoll)",
  "Humanoid (gnome)",
  "Humanoid (halfling)",
  "Humanoid (human)",
  "Humanoid (orc)",
  "Humanoid (reptilian)",
  "Magical Beast",
  "Monstrous Humanoid",
  "Ooze",
  "Outsider (air)",
  "Outsider (chaotic)",
  "Outsider (earth)",
  "Outsider (evil)",
  "Outsider (fire)",
  "Outsider (good)",
  "Outsider (lawful)",
  "Outsider (native)",
  "Outsider (water)",
  "Plant",
  "Undead",
  "Vermin"
];

const shitPlacesToLive = [
  "St Albans",
  "Hinchley Wood",
  "Widnes",
  "Barrow-in-Furness",
  "Skelmersdale",
  "Yate",
  "Bridgwater",
  "Alresford",
  "Slough",
  "Dagenham",
  "Keighley",
  "Hastings",
  "Huntington",
  "Maghull",
  "Reading",
  "Billingham",
  "Newport",
  "South Woodham Ferrers",
  "Dover",
  "Oxford",
  "Peterhead",
  "Tintern",
  "Mirfield",
  "Horsham",
  "Hayling Island",
  "Ipswich",
  "Leiston",
  "Aldeburgh",
  "Brighton",
  "Ascot",
  "Didcot",
  "Wolverhampton",
  "Peterborough",
  "London",
  "Islington",
  "Croydon",
  "St John's Wood",
  "Crouch End",
  "Stockport",
  "Portsmouth",
  "Hackney",
  "Basingstoke",
  "Beshill-on-sea",
  "St Andrews",
  "Liverpool",
  "Winchester",
  "Hythe",
  "Morecambe",
  "Cumbernauld",
  "Hull"
];

const sample = (arr) => arr[Math.floor(Math.random() * arr.length)]
const jobDescription = () => `${sample(tech)} ${sample(creatures)} in ${sample(shitPlacesToLive)}`;

document.addEventListener("DOMContentLoaded", function(event) {
  const anotherOne = () => {
    document.querySelector('#display').innerHTML = jobDescription();
  }
  document.querySelector('#hitme').addEventListener('click', anotherOne);
  anotherOne();
});
